apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-gv6m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ntor-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-gv6m@sha256:7485889260a2907ab8c434ff45d59b850ecbf06bc58a7a87d5475ea11346bf0d
        name: my-nodejs
        resources: {}
status: {}
